### ISSUE TITLE
Bug when loading events when using Neuropixels

### ISSUE THREAD

**Issue by MarineChap** [open-ephys/open-ephys-python-tools#1]
Hello, I am aware this is probably not ready for the public but I tried it anyway. :) So for info, I found a bug for you. 

After neuropixels recording my data folder looks like this: 

session: 
  - Record node 104
       - experiment2
            - recording1
                 - events
                     - Neuropix-PXI-105.0
                     - Phase_detector-106.0 
                  
When loading the event with this python tool, it crashed because it was (i guess) expecting the neuropixels folder to be name Neuropix_PXI-105.0 instead of Neuropix-PXI-105.0

Have a good day

**Comment by jsiegle** [comment]
Thanks, this is helpful! I will get this fixed soon.
