### ISSUE TITLE
global timestamps 

### ISSUE THREAD

**Issue by EmmettJT** [open-ephys/open-ephys-python-tools#19]
Hi, we recently upgraded to the latest open ephys (v0.6.4) and are now having issues aligning global timestamps. 

before this we are adding sync lines like so: 
```
session_data= Session(raw_data_directory)

synch_channel= 1
recording = session_data.recordnodes[0].recordings[0]

recording.add_sync_line(
    synch_channel,
    main_processor_tuple[0],
    main_processor_tuple[1],
    main=True,
)
for aux_processor in aux_processor_tuples:
    recording.add_sync_line(
        synch_channel,
        aux_processor[0],
        aux_processor[1],
        main=False,
    )

recording.compute_global_timestamps()
```

returns the following error:
![image](https://user-images.githubusercontent.com/43346332/234325697-e87060cf-c76e-42d4-b0bc-b1718d3249ec.png)

-------------------------
as a side note if we use ` session_data.recordnodes[0].recording[0] ` as written in the documentation this returns an error, we instead have to call recordings[0] [With an 's' at the end] - see code above
![image](https://user-images.githubusercontent.com/43346332/234326214-c2942a5d-97c4-497b-9e67-9e093fcdb16c.png)

**Comment by jsiegle** [comment]
Just updated the documentation, thanks for pointing that out!

@medengineer can you look into this error?

**Comment by medengineer** [comment]
Hi, I believe the second element in your processor tuples needs to be updated from stream index to stream name. This change was added in v0.1.3.

**Comment by EmmettJT** [comment]
Hi!

Thanks for the assistance! 

I changed the 'Stream Index' to the string name for each processor: eg. 'ProbeA-AP' rather than the number index. 

Unless I am looking at an outdated version of the documentation this is indicated wrong here so should be updated:  
![image](https://user-images.githubusercontent.com/43346332/235455091-5b6244e6-8ce0-431b-853b-ce7c53a9470c.png)

Thanks for your help!
