### ISSUE TITLE
oe_fast_loader.py uses a variable called "timestamps" but it is doesn't exist

### ISSUE THREAD

**Issue by nimrodlbr** [open-ephys/open-ephys-python-tools#20]
Hello, and thanks for this package and functionalities!

while trying to load events from a recording object I get the following:
===== code =====
c:......\site-packages\open_ephys\analysis\formats\helpers\oe_fast_loader.py in load_events(filename, recording_index)
    229     sample_numbers = np.array(np.memmap(filename, dtype='<i8', offset=1024, mode='r')[::2])
    230 
--> 231     data = np.memmap(filename, dtype='<u1', offset=1024, mode='r', shape=(len(timestamps), EVENT_RECORD_SIZE //2))
    232 
    233     recording_number = np.array(data[:,14])

NameError: name 'timestamps' is not defined
===== end code =====

This happened after updating to version 1.4

Is there a way around this? how is "timestamps" supposed to be defined? 

Thanks,
Nimrod

**Comment by medengineer** [comment]
Hello,

_timestamps_ should actually be _sample_numbers_ here.

The fix is included in the next release coming out later this week. 

Thanks!

**Comment by medengineer** [comment]
Fix is up and available for install here: https://pypi.org/project/open-ephys-python-tools/0.1.5/
