### ISSUE TITLE
Using open ephys python tools to monitor for errors

### ISSUE THREAD

**Issue by timsainb** [open-ephys/open-ephys-python-tools#24]
Hello,

I was wondering if it is possible to use open ephys python tools to monitor for an error that I'm having with the open ephys GUI.

Basically, I am recording 24/7 ephys and sending a TTL signal every 5 seconds as a 'sync' through an intan board. This works 99% of the time, but some small percentage of the time (say, once every 72 hours) my recording is corrupted because of the following error "Error in Rhd2000EvalBoard::readDataBlock: Incorrect header". I've tried to solve the error but since it's so rare I have trouble tracking it down. 

Why I would like to do is programatically watch for the error, and kill / restart open ephys recordings when the header becomes corrupted. Is this possible?

**Comment by jsiegle** [comment]
There's not a way to do this out of the box, but it could achieved with a small modification to the Acquisition Board plugin.

In [this section](https://github.com/open-ephys-plugins/rhythm-plugins/blob/c416a1341879a5b9b3c690f768d446d971c0abf6/Source/DeviceThread.cpp#L1788), before calling `break`, I think you'd just need to add the following lines of code:

```c++
uint64 ttlEventWord = 1 << 7;
int64 timestamp = 0;

sourceBuffers[0]->addToBuffer(thisSample,
                              &timestamp,
                              &ts,
                              &ttlEventWord,
                              1);
```

This will add a TTL event on line 8 (assuming that hardware input line is not used), which could be sent using the [Event Broadcaster](https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Event-Broadcaster.html) plugin and received using the [`streaming`](https://github.com/open-ephys/open-ephys-python-tools/blob/main/src/open_ephys/streaming/README.md) module. The callback from the `streaming` module could close and re-open the GUI.

Let me know if that makes sense!

**Comment by jsiegle** [comment]
At some point we will update the Event Broadcaster plugin to relay broadcast messages (instead of just TTL events and spikes) to external listeners, which would make this a lot simpler: https://github.com/open-ephys-plugins/event-broadcaster/issues/3

**Comment by timsainb** [comment]
Thanks Josh! I think while I wait for that feature I will do something a bit simpler and just write the output of open-ephys to a log and when the error prints, just restart the recording! Feel free to close unless you want to leave this open as a feature request.
