### ISSUE TITLE
How to trim recording?

### ISSUE THREAD

**Issue by LapishLab** [open-ephys/open-ephys-python-tools#25]
Hello, 

We're running into an issue where the timestamps become unstable at the end of each of our recordings in the last second or so. This is crashing our spike sorting pipeline due the inconsistencies in the timestamps. 

Is there a way to trim the end off a recording and all of the associated files (e.g. CH, ADC, AUX)?  

Thanks in advance, 

ccl

**Comment by LapishLab** [comment]
Thanks for the response. We're not looking to synchronize the data to any other sources currently. We just want to ignore the last second of the recording. In the image below, you can see the large jump in the sample interval time. We've discovered this in several of our data sets. Not sure what's causing it. 

<img width="541" alt="Screenshot 2023-10-16 at 1 10 50 PM" src="https://github.com/open-ephys/open-ephys-python-tools/assets/21068267/48caba61-9689-456c-ae25-2c0c0cc077d6">

**Comment by jsiegle** [comment]
I see...so it's just one data stream from an acquisition board? Is there a discontinuity in the continuous data (CH, ADC, AUX) at the same sample at which the timestamps jump?

**Comment by LapishLab** [comment]
Note that above is the voltage trace from 100_CH1.continuous

**Comment by jsiegle** [comment]
Ok, then trimming these files is the right way to go. What version of the GUI did you use to record this data?

It looks like there is one empty "record" (1024 samples) at the end of the file. Each record is 2070 bytes (documented [here](https://open-ephys.github.io/gui-docs/User-Manual/Recording-data/Open-Ephys-format.html#continuous)). So you can trim the files with the following code:

```python
record_size_in_bytes = 2070
data = np.memmap('100_CH1.continuous', mode='r', dtype='uint8')
total_bytes = len(data)
data[:total_bytes-record_size_in_bytes].tofile('100_CH1_trimmed.continuous')
```

Let me know if that works!

**Comment by LapishLab** [comment]
Thanks for the code. I'll let you know if it works. 

These data were acquired with Open Ephys Version 0.4.3.3. 

Thanks again!

**Comment by jsiegle** [comment]
Hi Nick – the last line in the example above will write a new file with the trimmed data. I'd recommend first backing up the original files, and then writing a new set of trimmed files with the same names. Then you can load the new files exactly as you would the original ones.

**Comment by nmtimme** [comment]
Hi @jsiegle,

Thank you for that clarification! I'm not super familiar with python and I missed that part of the code you posted. 

We're happy to report that trimming the .continuous files in this way resolved the error in spike interface and allowed spike sorting to progress. We have one follow-up question, though. How will this trimming impact the other support files (all_channels.events, Continuous_Data.openephys, messages.events, and settings.xml)? Do we need to modify these files in any way to make sure they agree with the trimmed .continuous files?

Thank you!

~Nick

**Comment by LapishLab** [comment]
@jsiegle this fix works well for us- thanks for the help.
