### ISSUE TITLE
Error: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by stef1029** [open-ephys/open-ephys-python-tools#29]
Hi,

I'm not sure if this is an issue with the tools themselves as it works well with my normal data, but I have a few recordings where it seems the settings.xml file didn't save for some reason, although I can't remember what was wrong with those recordings now unfortunately. The settings for the recordings were the same across all recordings so I tried copying the file over to the directory without to see if that would work but I'm still getting this error when I try and run the following code:
```python 
    def extract_ADC_data(self):
        self.recording = open_ephys.analysis.Session(self.dirname).recordnodes[0].recordings[0].continuous[0]
        self.samples = self.recording.samples   # raw samples, not in microvolts
        self.sample_numbers = self.recording.sample_numbers
        self.timestamps = self.recording.timestamps
        self.metadata = self.recording.metadata
```

My main question is whether you know if there is an easy work around/ what it is that I need to provide to in the files for this to work and so I can access the rest of the recordings.

Thanks for any help you can give,

Stefan

**Comment by medengineer** [comment]
Hi Stefan,

The settings.xml file isn't used while loading data so getting the same error with/without makes sense. It's possible that other files may be missing/incomplete. The error message here is not definitive.

Can you post the rest of the error traceback that contains line numbers / function names? Or if possible, send a link to download one of these datasets to pavel@open-ephys.org? You can zip a copy without the continuous data if size is an issue.

It would also be great to get a copy of the settings.xml to know what settings might have caused this.

Pavel

**Comment by stef1029** [comment]
Ok, I'll have a look and get back to you. I figured the error was a bit vague but interesting to know it's not the settings file.
Thanks,
Stefan

**Comment by stef1029** [comment]
Hi @medengineer ,

Here's a link to some files that are giving the error, and the full traceback too. Please note that the settings.xml file in that folder is not the original settings, and was copied from another folder that wasn't giving this error, so there might be details missing, however in the actual setup of the recording all the settings were the same. 

https://drive.google.com/drive/folders/1QXiJymLfun7Yf29QiyZy__tHSP9klho4?usp=drive_link

I'm not sure what's exactly caused the error but there were a few times where the recording buffer filled up and the recording stopped itself, and some other times where the computer filled it's storage and the recording stopped, but otherwise i can't think of any other strange recordings. 

Thanks for any help you can give,

Stefan

**Comment by stef1029** [comment]
Hi @medengineer , Just pinging this to see if you'd had a chance to look at this?

**Comment by medengineer** [comment]
Thanks for the ping, looks like I need permission to access the data, just send an email request. I can look at this today.

**Comment by stef1029** [comment]
Hi, have just given you permission, apologies for the delay as only just saw this response. Thanks for the help.

**Comment by medengineer** [comment]
Hi Stefan, 

I was able to reproduce the error and discovered there’s a mismatch between the recording index saved and the number of recordings in your dataset. This is likely due to the behaviour you described in the recording above.  

I sent you a link to the corrected dataset. I only changed the recording index for each block and not any actual ADC data. You can use your existing script to load this modified dataset.

Pavel

**Comment by stef1029** [comment]
Thanks very much for helping out with this, that's very helpful. I have a couple of other recordings where this was the case as well, is it easy to make this fix myself to those ones too? What do you mean specifically by the recording index?

**Comment by medengineer** [comment]
Open Ephys format can store multiple recordings (i.e. starting/stopping recording in the GUI multiple times) within a single file. The recording index is used to indicate which part of the file belongs to which recording. 

Assuming the rest of your recordings have only a single recording per file, you can ignore the recording index. The quickest (temporary) fix is to modify [this]( https://github.com/open-ephys/open-ephys-python-tools/blob/main/src/open_ephys/analysis/formats/helpers/oe_fast_loader.py#L160) line in the python-tools to

`valid_records = [True] * len(data[:, 5])`

This bypasses the recording index check and indicates all the blocks belong to the recording you want to load.

**Comment by stef1029** [comment]
Hi @medengineer
Just to update this thread, I made that change in a local copy of the python tools and installed that and it fixed the issue as intended, thanks for the help.
