### ISSUE TITLE
Set Record Directory controller

### ISSUE THREAD

**Issue by markschatza** [open-ephys/open-ephys-python-tools#4]
Not really the best place for this, but I noticed that you are not implementing the "set recording directory" and "append/prepend" text in the python controller. I'm assuming it doesn't play nice with the new record nodes. Any chance this going to come back sometime?

**Comment by jsiegle** [comment]
Yep! We can actually add this now, since the next release will restore that functionality for the new record node architecture.

**Comment by markschatza** [comment]
Great. Thanks!
